[project]
name = "test-partdiff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.2",
    "pytest-xdist[psutil]>=3.8.0",
]
